const VOZILA = [
  {
    id: 1,
    src: "../src/assets/images/vozila/1.jpg",
    marka: "Mercedes-Benz",
    model: "S-Class",
    godiste: 2024,
    tip: "limuzina",
    gorivo: "benzin",
    cena: 550,
    kolicina: 5,
  },
  {
    id: 2,
    src: "../src/assets/images/vozila/2.jpg",
    marka: "BMW",
    model: "Serija 7",
    godiste: 2023,
    tip: "limuzina ",
    gorivo: "dizel",
    cena: 600,
    kolicina: 4,
  },
  {
    id: 3,
    src: "../src/assets/images/vozila/3.jpg",
    marka: "Bentley",
    model: "Continental GT",
    godiste: 2023,
    tip: "sportski ",
    gorivo: "benzin",
    cena: 600,
    kolicina: 5,
  },
  {
    id: 4,
    src: "../src/assets/images/vozila/4.jpg",
    marka: "Mercedes",
    model: "G-Class",
    godiste: 2023,
    tip: "SUV ",
    gorivo: "benzin",
    cena: 550,
    kolicina: 6,
  },

  {
    id: 5,
    src: "../src/assets/images/vozila/5.jpg",
    marka: "Porsche",
    model: "911 Carrera",
    godiste: 2023,
    tip: "sportski",
    gorivo: "benzin",
    cena: 450,
    kolicina: 5,
  },

  {
    id: 6,
    src: "../src/assets/images/vozila/6.jpg",
    marka: "Audi",
    model: "R8",
    godiste: 2023,
    tip: "sportski",
    gorivo: "benzin",
    cena: 450,
    kolicina: 5,
  },

  {
    id: 7,
    src: "../src/assets/images/vozila/7.jpg",
    marka: "Audi",
    model: "A8",
    godiste: 2023,
    tip: "limuzina",
    gorivo: "dizel",
    cena: 450,
    kolicina: 5,
  },
  {
    id: 8,
    src: "../src/assets/images/vozila/8.jpg",
    marka: "Porsche",
    model: "Panamera",
    godiste: 2023,
    tip: "sportski",
    gorivo: "benzin",
    cena: 450,
    kolicina: 7,
  },
  {
    id: 9,
    src: "../src/assets/images/vozila/9.jpg",
    marka: "Lexus",
    model: "LS",
    godiste: 2022,
    tip: "limuzina",
    gorivo: "benzin",
    cena: 500,
    kolicina: 6,
  },
  {
    id: 10,
    src: "../src/assets/images/vozila/10.jpg",
    marka: "Lamborghini",
    model: "Urus",
    godiste: 2023,
    tip: "SUV ",
    gorivo: "benzin",
    cena: 600,
    kolicina: 5,
  },
  {
    id: 11,
    src: "../src/assets/images/vozila/11.jpg",
    marka: "Mercedes-Benz ",
    model: "Maybach S-Class",
    godiste: 2023,
    tip: "limuzina ",
    gorivo: "dizel",
    cena: 750,
    kolicina: 3,
  },
  {
    id: 12,
    src: "../src/assets/images/vozila/12.jpg",
    marka: "BMW",
    model: "X7",
    godiste: 2023,
    tip: "SUV ",
    gorivo: "dizel",
    cena: 550,
    kolicina: 10,
  },
];
export default VOZILA;
